# Generated by Django 3.1.7 on 2021-02-28 23:09

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileTag',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255, validators=[django.core.validators.ProhibitNullCharactersValidator()])),
            ],
            options={
                'verbose_name': 'profile tag',
                'verbose_name_plural': 'profile tags',
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='profiles.ProfileTag', verbose_name='tags'),
        ),
    ]
