# Generated by Django 3.1.7 on 2021-02-28 23:16

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20210228_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiletag',
            name='slug',
            field=models.SlugField(default='', max_length=255, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), 'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.', 'invalid')], verbose_name='slug'),
            preserve_default=False,
        ),
    ]
