# Generated by Django 3.1.7 on 2021-03-01 00:22

import app.profiles.types
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profiletag_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileAchievement',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='uuid')),
                ('type', models.CharField(choices=[('class attend', 'CLASS_ATTEND'), ('contribution', 'CONTRIBUTION')], default=app.profiles.types.ProfileAchievementTypes['CLASS_ATTEND'], max_length=255, verbose_name='type')),
                ('earned_at', models.DateTimeField(verbose_name='earned at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='updated at')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='deleted at')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='profiles.profile')),
            ],
            options={
                'verbose_name': 'profile achievement',
                'verbose_name_plural': 'profile achievements',
            },
        ),
    ]
