# Generated by Django 3.1.7 on 2021-03-03 22:41

import app.certificates.types
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='uuid')),
                ('certificate_category_weight', models.IntegerField(verbose_name='certificate category weight')),
                ('slug', models.SlugField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), 'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.', 'invalid')], verbose_name='slug')),
                ('status', models.CharField(choices=[('disabled', 'DISABLED'), ('active', 'ACTIVE')], default=app.certificates.types.CertificateStatuses['ACTIVE'], max_length=255, verbose_name='status')),
                ('type', models.CharField(choices=[('program', 'PROGRAM')], default=app.certificates.types.CertificateTypes['PROGRAM'], max_length=255, verbose_name='type')),
                ('name', models.CharField(max_length=255, validators=[django.core.validators.ProhibitNullCharactersValidator()])),
                ('description', models.TextField(blank=True, validators=[django.core.validators.ProhibitNullCharactersValidator()], verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='updated at')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='deleted at')),
            ],
            options={
                'verbose_name': 'certificate',
                'verbose_name_plural': 'certificates',
            },
        ),
        migrations.CreateModel(
            name='CertificateCategory',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='uuid')),
                ('slug', models.SlugField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), 'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.', 'invalid')], verbose_name='slug')),
                ('name', models.CharField(max_length=255, validators=[django.core.validators.ProhibitNullCharactersValidator()])),
                ('description', models.TextField(blank=True, validators=[django.core.validators.ProhibitNullCharactersValidator()], verbose_name='description')),
            ],
            options={
                'verbose_name': 'certificate category',
                'verbose_name_plural': 'certificate categories',
            },
        ),
        migrations.CreateModel(
            name='CertificateRequirement',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='uuid')),
                ('name', models.CharField(max_length=255, validators=[django.core.validators.ProhibitNullCharactersValidator()])),
                ('description', models.TextField(blank=True, validators=[django.core.validators.ProhibitNullCharactersValidator()], verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='updated at')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='deleted at')),
                ('certificate', models.ForeignKey(db_column='certificate_uuid', on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='certificates.certificate', verbose_name='certificate')),
            ],
            options={
                'verbose_name': 'certificate requirement',
                'verbose_name_plural': 'certificate requirements',
            },
        ),
        migrations.CreateModel(
            name='CertificateClaim',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='uuid')),
                ('type', models.CharField(choices=[('rejected', 'REJECTED'), ('awaiting approval', 'AWAITING_APPROVAL'), ('accepted', 'ACCEPTED')], default=app.certificates.types.CertificateClaimStatuses['AWAITING_APPROVAL'], max_length=255, verbose_name='type')),
                ('applied_at', models.DateTimeField(verbose_name='applied at')),
                ('response_issued_at', models.DateTimeField(null=True, verbose_name='response issued at')),
                ('response_comments', models.TextField(blank=True, validators=[django.core.validators.ProhibitNullCharactersValidator()], verbose_name='response comments')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='expires at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='updated at')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='deleted at')),
                ('certificate', models.ForeignKey(db_column='certificate_uuid', on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='certificates.certificate', verbose_name='certificate')),
            ],
            options={
                'verbose_name': 'certificate claim',
                'verbose_name_plural': 'certificate claims',
            },
        ),
    ]
