# Generated by Django 3.1.7 on 2021-03-01 00:25

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='name',
            field=models.CharField(default='', max_length=255, validators=[django.core.validators.ProhibitNullCharactersValidator()]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificate',
            name='slug',
            field=models.SlugField(default='', max_length=255, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), 'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.', 'invalid')], verbose_name='slug'),
            preserve_default=False,
        ),
    ]
