# Generated by Django 3.1.7 on 2021-03-01 22:53

import app.certificates.types
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profileachievement'),
        ('certificates', '0003_certificate_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='description',
            field=models.TextField(blank=True, validators=[django.core.validators.ProhibitNullCharactersValidator()], verbose_name='description'),
        ),
        migrations.CreateModel(
            name='CertificateRequirement',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='uuid')),
                ('name', models.CharField(max_length=255, validators=[django.core.validators.ProhibitNullCharactersValidator()])),
                ('description', models.TextField(blank=True, validators=[django.core.validators.ProhibitNullCharactersValidator()], verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='updated at')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='deleted at')),
                ('certificate', models.ForeignKey(db_column='certificate_uuid', on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='certificates.certificate', verbose_name='certificate')),
            ],
            options={
                'verbose_name': 'certificate requirement',
                'verbose_name_plural': 'certificate requirements',
            },
        ),
        migrations.CreateModel(
            name='CertificateClaim',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='uuid')),
                ('type', models.CharField(choices=[('rejected', 'REJECTED'), ('awaiting approval', 'AWAITING_APPROVAL'), ('accepted', 'ACCEPTED')], default=app.certificates.types.CertificateClaimStatuses['AWAITING_APPROVAL'], max_length=255, verbose_name='type')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='updated at')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='deleted at')),
                ('certificate', models.ForeignKey(db_column='certificate_uuid', on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='certificates.certificate', verbose_name='certificate')),
                ('profile', models.ForeignKey(db_column='profile_uuid', on_delete=django.db.models.deletion.CASCADE, related_name='certificate_claims', to='profiles.profile', verbose_name='profile')),
            ],
            options={
                'verbose_name': 'certificate claim',
                'verbose_name_plural': 'certificate claims',
            },
        ),
    ]
